/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Conexion.ClienteRepositorio;
import Modelos.Cliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;

/**
 *
 * @author David
 */
public class ConsultarCliente extends javax.swing.JPanel {

    private Conexion.ClienteRepositorio repo;

    /**
     * Creates new form ConsultarCliente
     */
    public ConsultarCliente() {
        initComponents();
        repo = new ClienteRepositorio();
        ClienteRepositorio clienteRepo = new ClienteRepositorio();

// Crear popup y modelo para sugerencias de cliente
        DefaultListModel<String> modeloClientes = new DefaultListModel<>();
        JList<String> listaClientes = new JList<>(modeloClientes);
        JPopupMenu popupClientes = new JPopupMenu();
        popupClientes.add(new JScrollPane(listaClientes));

// Evento: cuando el usuario escribe en el campo DNI
        dnicliente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = dnicliente.getText().trim();
                modeloClientes.clear();

                if (!texto.isEmpty()) {
                    List<Cliente> resultados = clienteRepo.buscarPorDniParcial(texto);
                    for (Cliente c : resultados) {
                        modeloClientes.addElement(c.getDni() + " - " + c.getNombre());
                    }

                    if (!modeloClientes.isEmpty()) {
                        listaClientes.setSelectedIndex(0);
                        popupClientes.show(dnicliente, 0, dnicliente.getHeight());
                    } else {
                        popupClientes.setVisible(false);
                    }
                } else {
                    popupClientes.setVisible(false);
                }
            }
        });

// Evento: cuando se hace clic en una sugerencia
        listaClientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    String seleccionado = listaClientes.getSelectedValue();
                    if (seleccionado != null && seleccionado.contains(" - ")) {
                        String dniSeleccionado = seleccionado.split(" - ")[0].trim();
                        Cliente cliente = clienteRepo.buscarPorDni(dniSeleccionado);

                        if (cliente != null) {
                            dnicliente.setText(String.valueOf(cliente.getDni()));
                            nombreCliente.setText(cliente.getNombre());
                            telefonoCliente.setText(cliente.getTelefono());
                        }
                        popupClientes.setVisible(false);
                    }
                }
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dnicliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosCliente = new javax.swing.JTextArea();
        botonBuscarCliente = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa el DNI del cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 214, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("DNI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 71, 103, 36));

        dnicliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniclienteActionPerformed(evt);
            }
        });
        add(dnicliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 114, 219, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre completo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 153, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 137, 44));

        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });
        add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 219, 41));

        telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteActionPerformed(evt);
            }
        });
        add(telefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 222, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Pedidos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 162, 42));

        pedidosCliente.setColumns(20);
        pedidosCliente.setRows(5);
        jScrollPane1.setViewportView(pedidosCliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 607, 210));

        botonBuscarCliente.setBackground(new java.awt.Color(255, 153, 255));
        botonBuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarCliente.setText("Buscar clienteeee");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });
        add(botonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 106, 221, 47));
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        String dni = dnicliente.getText() != null ? dnicliente.getText().trim() : "";
        if (dni.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un DNI.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1) Buscar datos del cliente
        Cliente cliente = repo.buscarPorDni(dni);
        if (cliente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente no encontrado con DNI: " + dni, "No encontrado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // limpiar campos
            nombreCliente.setText("");
            telefonoCliente.setText("");
            pedidosCliente.setText("");
            return;
        }

        // llenar campos
        nombreCliente.setText(cliente.getNombre() != null ? cliente.getNombre() : "");
        telefonoCliente.setText(cliente.getTelefono() != null ? cliente.getTelefono() : "");

        // 2) obtener id_cliente y luego listar pedidos
        Integer idCliente = repo.getIdClienteByDni(dni);
        if (idCliente == null) {
            pedidosCliente.setText("No se pudo obtener id_cliente.");
            return;
        }

        List<String> pedidos = repo.listarPedidosPorClienteId(idCliente);
        if (pedidos == null || pedidos.isEmpty()) {
            pedidosCliente.setText("No tiene pedidos registrados.");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String linea : pedidos) {
                sb.append(linea).append(System.lineSeparator());
            }
            pedidosCliente.setText(sb.toString());
        }
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void dniclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniclienteActionPerformed

    }//GEN-LAST:event_dniclienteActionPerformed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed

    }//GEN-LAST:event_nombreClienteActionPerformed

    private void telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteActionPerformed

    }//GEN-LAST:event_telefonoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JTextField dnicliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextArea pedidosCliente;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
