/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Conexion.ProductoRepositorio;
import Modelos.Producto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class ConsultarInventario extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarInventario
     */
    public ConsultarInventario() {
        initComponents();
        cargarTabla();
    }

    private void cargarTabla() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Nombre", "Precio", "Categoría"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ProductoRepositorio repo = new ProductoRepositorio();
        List<Producto> lista = repo.listarProductos();
        for (Producto p : lista) {
            model.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getPrecio(), p.getCategoria()});
        }
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botoneliminarClientes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INVENTARIO");

        botoneliminarClientes.setBackground(new java.awt.Color(255, 0, 204));
        botoneliminarClientes.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botoneliminarClientes.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminarClientes.setText("ELIMINAR PRODUCTO");
        botoneliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(botoneliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoneliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoneliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarClientesActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto a eliminar.");
            return;
        }
        int id = (int) jTable1.getValueAt(fila, 0);
        ProductoRepositorio repo = new ProductoRepositorio();

        int refs = repo.contarReferencias(id); // si aún tienes ese método
        if (refs > 0) {
            String mensaje = String.format(
                    "Este producto tiene %d referencias en otras tablas (compras/ventas/pedidos/ingredientes).\n"
                    + "Si borras el producto también se eliminarán esas referencias.\n\n¿Deseas continuar y eliminar todo?",
                    refs
            );
            int opt = JOptionPane.showConfirmDialog(this, mensaje, "Confirmar eliminación con dependencias", JOptionPane.YES_NO_OPTION);
            if (opt != JOptionPane.YES_OPTION) {
                return;
            }
        } else {
            if (JOptionPane.showConfirmDialog(this, "Eliminar producto ID " + id + " ?", "Confirmar", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }
        }

        boolean ok = repo.eliminarConDependencias(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Producto y sus referencias eliminadas correctamente.");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar. Revisa la consola para más detalles.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botoneliminarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminarClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
