/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Conexion.PedidoRepositorio;
import Modelos.Reportes;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author David
 */
public class GenerarReportes extends javax.swing.JPanel {

    /**
     * Creates new form GenerarReportes
     */
    public GenerarReportes() {
        initComponents();
        PedidoRepositorio repo = new PedidoRepositorio();
        List<Reportes> datos = repo.obtenerReportes();

        cargarTabla(datos);
    }

    public void generarExcel(List<Reportes> lista) {
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar Reporte");
            fileChooser.setSelectedFile(new File("ReportePedidos.xlsx"));

            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {

                File archivo = fileChooser.getSelectedFile();
                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("Reporte");

                Row header = sheet.createRow(0);
                header.createCell(0).setCellValue("Cliente");
                header.createCell(1).setCellValue("Producto");
                header.createCell(2).setCellValue("Cantidad");
                header.createCell(3).setCellValue("Precio");
                header.createCell(4).setCellValue("Total");

                int fila = 1;

                for (Reportes r : lista) {
                    Row row = sheet.createRow(fila++);
                    row.createCell(0).setCellValue(r.getCliente());
                    row.createCell(1).setCellValue(r.getProducto());
                    row.createCell(2).setCellValue(r.getCantidad());
                    row.createCell(3).setCellValue(r.getPrecio());
                    row.createCell(4).setCellValue(r.getTotal());
                }

                FileOutputStream out = new FileOutputStream(archivo);
                workbook.write(out);
                out.close();
                workbook.close();

                JOptionPane.showMessageDialog(null, "Reporte generado correctamente.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    public void cargarTabla(List<Reportes> lista) {

        String[] columnas = {"Cliente", "Producto", "Cantidad", "Precio", "Total"};

        Object[][] datos = new Object[lista.size()][5];

        for (int i = 0; i < lista.size(); i++) {
            Reportes r = lista.get(i);
            datos[i][0] = r.getCliente();
            datos[i][1] = r.getProducto();
            datos[i][2] = r.getCantidad();
            datos[i][3] = r.getPrecio();
            datos[i][4] = r.getTotal();
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                columnas
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonImprimirReporte = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REPORTE DE VENTAS");

        botonImprimirReporte.setBackground(new java.awt.Color(255, 0, 204));
        botonImprimirReporte.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonImprimirReporte.setForeground(new java.awt.Color(255, 255, 255));
        botonImprimirReporte.setText("IMPRIMIR REPORTE");
        botonImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(botonImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirReporteActionPerformed
        PedidoRepositorio repo = new PedidoRepositorio();
        List<Reportes> datos = repo.obtenerReportes();

        System.out.println("Tamaño de la lista: " + datos.size());
        for (Reportes r : datos) {
            System.out.println(r.getCliente() + " - " + r.getProducto());
        }

        generarExcel(datos);


    }//GEN-LAST:event_botonImprimirReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImprimirReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
