/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Conexion.EmpleadoRepositorio;
import Modelos.Empleado;
import java.time.LocalDate;

/**
 *
 * @author David
 */
public class RegistrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEmpleado
     */
    public RegistrarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        apellidotxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefonoEmpleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        correoEmpleado = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sueldoEmpleado = new javax.swing.JTextPane();
        botonRegistrarEmpleado = new javax.swing.JButton();
        cargoBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DATOS DEL EMPLEADO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 13, 177, 47));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 67, 110, 41));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 67, 150, 41));
        add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 44));
        add(apellidotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 115, 219, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefono:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 177, 105, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("DNI:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 185, 166, -1));
        add(telefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, 39));

        jScrollPane1.setViewportView(correoEmpleado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 219, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sueldo:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 267, 139, 42));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cargo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 129, 42));

        jScrollPane2.setViewportView(sueldoEmpleado);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 39));

        botonRegistrarEmpleado.setBackground(new java.awt.Color(255, 153, 255));
        botonRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarEmpleado.setText("Registrar empleado");
        botonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEmpleadoActionPerformed(evt);
            }
        });
        add(botonRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 524, 219, 43));

        cargoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesero", "Cajero", "Almacen", "Cocinero", "Delivery", "Limpieza" }));
        add(cargoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 316, 119, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Correo:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 166, -1));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 221, 219, 39));
    }// </editor-fold>//GEN-END:initComponents
private void limpiarCampos() {
        nombretxt.setText("");
        apellidotxt.setText("");
        telefonoEmpleado.setText("");
        correoEmpleado.setText("");
        sueldoEmpleado.setText("");
        txtDni.setText("");
        cargoBox.setSelectedIndex(0); // vuelve al primer cargo
    }
    private void botonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEmpleadoActionPerformed
        try {
            int dni = Integer.parseInt(txtDni.getText());
            String nombre = nombretxt.getText();
            String apellidos = apellidotxt.getText(); // (tu campo parece ser "dniEmpleado", pero en tu diseño realmente almacena los apellidos)
            String telefono = telefonoEmpleado.getText();
            String correo = correoEmpleado.getText();
            double sueldo = Double.parseDouble(sueldoEmpleado.getText());
            String cargo = cargoBox.getSelectedItem().toString();
            LocalDate fechaIngreso = LocalDate.now();
            String contraseña = nombre.toLowerCase() + "123"; // 🔐 ejemplo automático, puedes cambiarlo

            // Crear objeto Empleado
            Empleado emp = new Empleado(dni, nombre, apellidos, cargo, telefono, correo, sueldo, fechaIngreso, contraseña);

            // Registrar en base de datos
            EmpleadoRepositorio repo = new EmpleadoRepositorio();
            boolean exito = repo.registrarEmpleado(emp);

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Empleado registrado con éxito");
                limpiarCampos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "❌ Error al registrar empleado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidotxt;
    private javax.swing.JButton botonRegistrarEmpleado;
    private javax.swing.JComboBox<String> cargoBox;
    private javax.swing.JTextPane correoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextPane sueldoEmpleado;
    private javax.swing.JTextField telefonoEmpleado;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
