/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author David
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        mostrar(new RegistrarPedido());
    }
public void mostrar (JPanel j){
        j.setSize(720, 600); // Ajusta el tamaño al del panel 'muestra'
        j.setLocation(0, 0);
        
        muestra.removeAll();
        muestra.setLayout(new BorderLayout()); 
        muestra.add(j, BorderLayout.CENTER);
        muestra.revalidate();
        muestra.repaint();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vista = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        botonRegistrarPedido = new javax.swing.JButton();
        botonModificarPedido = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonEliminarPedido = new javax.swing.JButton();
        botonRegistrarEmpleado = new javax.swing.JButton();
        botonGestionarInventario = new javax.swing.JButton();
        botonConsultarCliente = new javax.swing.JButton();
        botonGenerarReporte = new javax.swing.JButton();
        muestra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        vista.setBackground(new java.awt.Color(255, 255, 255));
        vista.setName(""); // NOI18N

        Menu.setBackground(new java.awt.Color(255, 204, 255));

        botonRegistrarPedido.setBackground(new java.awt.Color(255, 153, 255));
        botonRegistrarPedido.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonRegistrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarPedido.setText("Registrar pedidos");
        botonRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPedidoActionPerformed(evt);
            }
        });

        botonModificarPedido.setBackground(new java.awt.Color(255, 153, 255));
        botonModificarPedido.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonModificarPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonModificarPedido.setText("Modificar pedidos");
        botonModificarPedido.setToolTipText("");
        botonModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPedidoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        botonEliminarPedido.setBackground(new java.awt.Color(255, 153, 255));
        botonEliminarPedido.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonEliminarPedido.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarPedido.setText("Eliminar pedido");
        botonEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPedidoActionPerformed(evt);
            }
        });

        botonRegistrarEmpleado.setBackground(new java.awt.Color(255, 153, 255));
        botonRegistrarEmpleado.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarEmpleado.setText("Registrar Empleado");
        botonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        botonGestionarInventario.setBackground(new java.awt.Color(255, 153, 255));
        botonGestionarInventario.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonGestionarInventario.setForeground(new java.awt.Color(255, 255, 255));
        botonGestionarInventario.setText("Gestionar inventario");
        botonGestionarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarInventarioActionPerformed(evt);
            }
        });

        botonConsultarCliente.setBackground(new java.awt.Color(255, 153, 255));
        botonConsultarCliente.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonConsultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarCliente.setText("Consultar clientes");
        botonConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarClienteActionPerformed(evt);
            }
        });

        botonGenerarReporte.setBackground(new java.awt.Color(255, 153, 255));
        botonGenerarReporte.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        botonGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        botonGenerarReporte.setText("Generar reportes");
        botonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonModificarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonGestionarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botonRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(botonEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGestionarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        muestra.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout muestraLayout = new javax.swing.GroupLayout(muestra);
        muestra.setLayout(muestraLayout);
        muestraLayout.setHorizontalGroup(
            muestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        muestraLayout.setVerticalGroup(
            muestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vistaLayout = new javax.swing.GroupLayout(vista);
        vista.setLayout(vistaLayout);
        vistaLayout.setHorizontalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(muestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        vistaLayout.setVerticalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaLayout.createSequentialGroup()
                .addComponent(muestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPedidoActionPerformed
       mostrar(new RegistrarPedido());
    }//GEN-LAST:event_botonRegistrarPedidoActionPerformed

    private void botonModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPedidoActionPerformed
        mostrar(new ModificarPedido());
    }//GEN-LAST:event_botonModificarPedidoActionPerformed

    private void botonEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPedidoActionPerformed
       mostrar(new EliminarPedido());
    }//GEN-LAST:event_botonEliminarPedidoActionPerformed

    private void botonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEmpleadoActionPerformed
        mostrar(new RegistrarPedido()); 
    }//GEN-LAST:event_botonRegistrarEmpleadoActionPerformed

    private void botonGestionarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarInventarioActionPerformed
        mostrar(new ConsultarInventario());
    }//GEN-LAST:event_botonGestionarInventarioActionPerformed

    private void botonConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarClienteActionPerformed
       mostrar(new ConsultarCliente());
    }//GEN-LAST:event_botonConsultarClienteActionPerformed

    private void botonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReporteActionPerformed
        mostrar(new GenerarReportes());
    }//GEN-LAST:event_botonGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton botonConsultarCliente;
    private javax.swing.JButton botonEliminarPedido;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonGestionarInventario;
    private javax.swing.JButton botonModificarPedido;
    private javax.swing.JButton botonRegistrarEmpleado;
    private javax.swing.JButton botonRegistrarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel muestra;
    private javax.swing.JPanel vista;
    // End of variables declaration//GEN-END:variables
}
